# Generated by Django 2.2 on 2019-07-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='电子邮箱')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='用户名')),
                ('sex', models.CharField(choices=[(0, '男'), (1, '女')], max_length=2, verbose_name='性别')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
                ('info', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人介绍')),
                ('user_image', models.ImageField(blank=True, default='', null=True, upload_to='user/%Y%m%d', verbose_name='用户头像')),
                ('register_data', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('disread_reply_counts', models.IntegerField(verbose_name='未读回复数')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='User_like_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Topic', verbose_name='被点赞话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '话题点赞表',
                'verbose_name_plural': '话题点赞表',
            },
        ),
        migrations.CreateModel(
            name='User_like_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Reply', verbose_name='被点赞回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '回复点赞表',
                'verbose_name_plural': '回复点赞表',
            },
        ),
    ]
