# Generated by Django 2.2 on 2019-07-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190726_2219'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_like_reply',
            old_name='topic',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='user_like_reply',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='该回复的主人是否已读'),
        ),
        migrations.AddField(
            model_name='user_like_topic',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='该话题的主人是否已读'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disread_reply_counts',
            field=models.IntegerField(default=0, verbose_name='未读回复数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='User_like_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='该评论的主人是否已读')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Comment', verbose_name='被点赞评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '评论点赞表',
                'verbose_name_plural': '评论点赞表',
            },
        ),
    ]
