# Generated by Django 2.2 on 2019-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190726_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True, verbose_name='电子邮箱'),
        ),
    ]
