# Generated by Django 2.2 on 2019-07-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190726_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='open_id',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='用户唯一id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.CharField(max_length=200, verbose_name='用户头像'),
        ),
    ]
