# Generated by Django 2.2 on 2019-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190727_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户唯一id'),
        ),
    ]
