# Generated by Django 2.2 on 2019-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190727_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话'),
        ),
    ]
