# Generated by Django 2.2 on 2019-08-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190802_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='register_data',
            new_name='register_date',
        ),
    ]
