# Generated by Django 2.2 on 2019-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190804_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_like_reply',
        ),
    ]
