# Generated by Django 2.2 on 2019-08-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_user_like_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disread_reply_counts',
        ),
    ]
