# Generated by Django 2.2 on 2019-08-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_school_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='true_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='真实姓名'),
        ),
    ]
