# Generated by Django 2.2 on 2019-08-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_true_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_id_new',
            field=models.CharField(default='', max_length=50, verbose_name='公众号用户唯一id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='小程序用户唯一id'),
        ),
    ]
