# Generated by Django 2.2 on 2019-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190819_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(default='', max_length=50, verbose_name='小程序用户唯一id'),
        ),
    ]
