# Generated by Django 2.2 on 2019-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190824_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image_local',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/%Y/%m/%d', verbose_name='用户头像(本地)'),
        ),
    ]
