# Generated by Django 2.2 on 2019-08-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_user_image_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='open_id_new',
        ),
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='小程序用户唯一id'),
        ),
    ]
