# Generated by Django 2.2 on 2019-08-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(choices=[(0, '学生工作'), (1, '校园交流')], verbose_name='所属类别')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('date', models.DateField(verbose_name='发布时间')),
                ('detail_image_url', models.CharField(max_length=100, verbose_name='云存储url')),
                ('view_counts', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name': '公文通',
                'verbose_name_plural': '公文通',
            },
        ),
    ]
