# Generated by Django 2.2 on 2019-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='part',
            field=models.IntegerField(choices=[(0, '学生工作'), (1, '校园生活')], verbose_name='所属类别'),
        ),
    ]
