# Generated by Django 2.2 on 2019-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20190813_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='版本号')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('android_apk_url', models.CharField(max_length=200, verbose_name='安卓下载地址')),
                ('ios_apk_url', models.CharField(max_length=200, verbose_name='IOS下载地址')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
            },
        ),
    ]
