# Generated by Django 2.2 on 2019-09-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0023_auto_20190828_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif_play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Gif系统名')),
                ('name_to_user', models.CharField(max_length=20, verbose_name='Gif图名字(面向用户)')),
                ('sentence_counts', models.IntegerField(default=0, verbose_name='句子数量')),
                ('gif_url', models.CharField(max_length=200, verbose_name='动图的url')),
            ],
            options={
                'verbose_name': '动图制作',
                'verbose_name_plural': '动图制作',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '打卡小分队'), (1, '狼人杀'), (2, '真心话大冒险')], default=0, verbose_name='房间类型')),
                ('number', models.CharField(max_length=10, verbose_name='房间号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('topic', models.CharField(max_length=50, verbose_name='房间主题')),
                ('max_user_counts', models.IntegerField(default=20, verbose_name='最大人数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='房主id')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
        migrations.CreateModel(
            name='User_in_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('role', models.CharField(default='未分配', max_length=10, verbose_name='角色')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Room', verbose_name='加入的房间id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户加入房间表',
                'verbose_name_plural': '用户加入房间表',
            },
        ),
    ]
