# Generated by Django 2.2 on 2019-09-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif_play',
            name='picture_url',
            field=models.CharField(default='', max_length=200, verbose_name='封面图片的url'),
        ),
    ]
