# Generated by Django 2.2.5 on 2019-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gif_play_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_in_room',
            name='is_room_master',
            field=models.BooleanField(default=False, verbose_name='是否为房主'),
        ),
    ]
