# Generated by Django 2.2 on 2019-07-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='回复内容')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('image', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='回复图片')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='板块名')),
                ('introduce', models.CharField(max_length=200, verbose_name='板块介绍')),
                ('article_counts', models.IntegerField(verbose_name='板块文章总数')),
                ('self_counts', models.IntegerField(verbose_name='板块点击数')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_data', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('header', models.CharField(max_length=16, verbose_name='话题标题')),
                ('content', models.CharField(max_length=1000, verbose_name='话题内容')),
                ('reply_counts', models.IntegerField(verbose_name='话题回复数')),
                ('self_counts', models.IntegerField(verbose_name='话题点击数')),
                ('great_counts', models.IntegerField(verbose_name='点赞数')),
                ('in_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Session', verbose_name='所在板块')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
            },
        ),
        migrations.CreateModel(
            name='Topic_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片1')),
                ('image_2', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片2')),
                ('image_3', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片3')),
                ('image_4', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片4')),
                ('image_5', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片5')),
                ('image_6', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片6')),
                ('image_7', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片7')),
                ('image_8', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片8')),
                ('image_9', models.ImageField(default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='话题图片9')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Topic', verbose_name='图片所在话题')),
            ],
            options={
                'verbose_name': '话题图片',
                'verbose_name_plural': '话题图片',
            },
        ),
    ]
