# Generated by Django 2.2 on 2019-07-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='reply',
            name='in_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Topic', verbose_name='所在话题'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Reply', verbose_name='评论回复'),
        ),
        migrations.AddField(
            model_name='reply',
            name='replyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='回复者'),
        ),
    ]
