# Generated by Django 2.2 on 2019-07-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190726_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='image',
        ),
    ]
