# Generated by Django 2.2 on 2019-07-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190726_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
    ]
