# Generated by Django 2.2 on 2019-07-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190726_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replyer',
            new_name='commenter',
        ),
    ]
