# Generated by Django 2.2 on 2019-07-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190726_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '版块', 'verbose_name_plural': '版块'},
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Comment/%Y%m%d', verbose_name='评论图片'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Reply/%Y%m%d', verbose_name='回复图片'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Reply', verbose_name='评论回复的回复'),
        ),
        migrations.AddField(
            model_name='session',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Session/logo', verbose_name='版块logo'),
        ),
        migrations.AlterField(
            model_name='session',
            name='article_counts',
            field=models.IntegerField(default=0, verbose_name='版块文章总数'),
        ),
        migrations.AlterField(
            model_name='session',
            name='introduce',
            field=models.CharField(max_length=200, verbose_name='版块介绍'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='版块名'),
        ),
        migrations.AlterField(
            model_name='session',
            name='self_counts',
            field=models.IntegerField(default=0, verbose_name='版块点击数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='in_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Session', verbose_name='所在版块'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y%m%d', verbose_name='话题图片1'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y%m%d', verbose_name='话题图片2'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y%m%d', verbose_name='话题图片3'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y%m%d', verbose_name='话题图片4'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y%m%d', verbose_name='话题图片5'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y%m%d', verbose_name='话题图片6'),
        ),
    ]
