# Generated by Django 2.2 on 2019-08-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190727_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='header',
            new_name='title',
        ),
    ]
