# Generated by Django 2.2 on 2019-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190802_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='image',
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=40, verbose_name='话题标题'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片1'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片2'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片3'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片4'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片5'),
        ),
        migrations.AlterField(
            model_name='topic_image',
            name='image_6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片6'),
        ),
    ]
