# Generated by Django 2.2 on 2019-08-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190804_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_image',
            name='image_6',
        ),
        migrations.AddField(
            model_name='topic_image',
            name='image_0',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Topic/%Y/%m/%d', verbose_name='话题图片1'),
        ),
    ]
