# Generated by Django 2.2 on 2019-08-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190804_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_image',
            old_name='image_0',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='topic_image',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='topic_image',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='topic_image',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='topic_image',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='topic_image',
            name='image_5',
        ),
    ]
