# Generated by Django 2.2 on 2019-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190805_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='great_counts',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.IntegerField(default=1, verbose_name='评论的楼数'),
        ),
    ]
