# Generated by Django 2.2 on 2019-08-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_user_like_reply'),
        ('article', '0016_auto_20190806_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='reply',
            name='be_replyer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_replyer', to='user.User', verbose_name='被回复者'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyer', to='user.User', verbose_name='回复者'),
        ),
    ]
