# Generated by Django 2.2 on 2019-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20190806_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_image',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='云存储url'),
        ),
    ]
