# Generated by Django 2.2 on 2019-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_topic_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='版块logo的url'),
        ),
    ]
