# Generated by Django 2.2 on 2019-08-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_session_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='url',
            new_name='logo_url',
        ),
        migrations.RemoveField(
            model_name='session',
            name='logo',
        ),
    ]
