# Generated by Django 2.2 on 2019-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20190809_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.CharField(max_length=5000, verbose_name='话题内容'),
        ),
    ]
