# Generated by Django 2.2 on 2019-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20190810_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='model_class',
            field=models.IntegerField(choices=[(0, '生活'), (1, '学习')], default=0, verbose_name='版块类别'),
        ),
    ]
