# Generated by Django 2.2 on 2019-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_session_can_user_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='color',
            field=models.CharField(default='', max_length=30, verbose_name='版块颜色'),
        ),
    ]
