# Generated by Django 2.2 on 2019-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20190819_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='model_class',
            field=models.IntegerField(choices=[(0, '生活'), (1, '学习'), (2, '事务')], default=0, verbose_name='版块类别'),
        ),
    ]
